### ISSUE TITLE
最新版本无法选择存储文件夹？

### ISSUE THREAD

**Issue by KNH-MaoMao** [Hitachi-Momoka/krkrfgformatWPF#1]
我打开好几次选择存储文件夹都是灰的.....

**Comment by Hitachi-Momoka** [comment]
确实，因为感觉并不支持批量合成导出，所以感觉没啥用，支持的话，还得支持info文件的读取，而且文件里面的文本的格式并不统一，太麻烦了，一直想写，也一直没动手，所以就没写相关的代码。UI是根据别人的布局写的，所以多了个按钮。

**Comment by KNH-MaoMao** [comment]
> 确实，因为感觉并不支持批量合成导出，所以感觉没啥用，支持的话，还得支持info文件的读取，而且文件里面的文本的格式并不统一，太麻烦了，一直想写，也一直没动手，所以就没写相关的代码。UI是根据别人的布局写的，所以多了个按钮。

原来如此....感谢回复
